Metadata-Version: 2.1
Name: friendly-custom-exception
Version: 0.0.1
Summary: Showing how to add custom exceptions to friendly-traceback
Home-page: https://github.com/friendly-traceback/friendly-custom-exception
Author: Andre Roberge
Author-email: Andre.Roberge@gmail.com
Classifier: Development Status :: 1 - Planning
Classifier: Environment :: Console
Classifier: License :: OSI Approved :: MIT License
Classifier: Natural Language :: English
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.8
Classifier: Programming Language :: Python :: 3.9
Classifier: Programming Language :: Python :: 3.10
Classifier: Intended Audience :: Education
Classifier: Topic :: Education
Requires-Python: >=3.8
Description-Content-Type: text/markdown
License-File: LICENSE
Requires-Dist: friendly (>=0.5.35)
Requires-Dist: jupyter

# friendly-custom-exception

This is a demo project that illustrates how one can add
the required information so that friendly-traceback can
provide explanations for custom exceptions. By custom
exception, we mean any exception that either is not 
raised by Python modules from the standard library or
or that are raised with different messages specific
to a given library.
